config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'pins#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pin.rb
class Pin < ApplicationRecord
  validates_presence_of :description
  belongs_to :user

  has_one_attached :pin_image
  validate :correct_pin_image

  private

  def correct_pin_image
    if pin_image.attached? && !pin_image.content_type.in?(%w(image/jpeg image/png image/gif image/webp))
        errors.add(:pin_image, 'needs to be a JPEG, PNG, GIF or WEBP')
    elsif pin_image.attached? == false
        errors.add(:pin_image, 'must have an image attached.')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pagy::Backend
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /pins or /pins.json
  def index
    # @pins = Pin.all
    @pagy, @pins = pagy_countless(Pin.order(created_at: :desc), items: 5)
    respond_to do |format|
      format.html # GET
      format.turbo_stream # POST
    end
    # if params[:page]
    #   render "scrollable_list"
    # end
  end

  # GET /pins/1 or /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins or /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to pin_url(@pin), notice: "Pin was successfully created." }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1 or /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to pin_url(@pin), notice: "Pin was successfully updated." }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1 or /pins/1.json
  def destroy
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url, notice: "Pin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pin_params
      params.require(:pin).permit(:description, :pin_image)
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtDream</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_import_module_tag "scroll" %>

    <%# <%= yield(:head) %>

  </head>

  <body>
  <header class="p-3 bg-dark text-white">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="0" height="32" role="img" aria-label="Logo"><%= image_tag("logo.svg", size: "50x42") %></svg>
          <span class="fs-4">ArtDream</span>
        </a>
        <ul class="nav col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0 mt-1">
          <li> <%= link_to "New pin", new_pin_path,  class: "nav-link px-2 text-white"%> </li>
        </ul>

        <%# <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form> %>

        <div class="text-end">
          <% if user_signed_in? %>
            <%= link_to "Logout", destroy_user_session_path, class: "btn btn-outline-light me-2", 'data-turbo-method': :delete%>
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "btn btn-warning" %>
          <% else %>
            <%= link_to 'Login', new_user_session_path, class: "btn btn-outline-light me-2" %>
            <%= link_to 'Sign-up', new_user_registration_path, class: "btn btn-warning" %>
          <% end %>
        </div>
      </div>
  </header>

    <%# <div class = "container"> %>
      <%# <p class="notice"><%= notice %></p>
      <%# <p class="alert"><%= alert %></p>
      <%= yield %>
    <%# </div> %>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin) do |form| %>
  <% if pin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
        <% pin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description, style: "display: block" %><br>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :pin_image %><br>
    <%= form.file_field :pin_image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<%# <div id="<%= dom_id pin"> %>
  <%# <p> %>
    <%# <%= pin.description %>
  <%# </p> %>

  <%# <% if pin.pin_image.attached? %>
    <%# <%= image_tag(pin.pin_image, style:"") %>
  <%# <% end %>
<%# </div> %>

 <%= link_to pin do %>
    <div class="pin_img">
      <%= image_tag(pin.pin_image, class:"img-responsive", width: '100%') %>
        <div class="pin_user_content">
          <p><%= pin.user.username %></p>
        </div>
        <div class="pin_content">
          <p><%= pin.description%></p>
        </div>

    </div>
<%# <%= link_to "Show this pin", pin%>
  <% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render "form", pin: @pin %>

<br>

<div>
  <%= link_to "Show this pin", @pin %> |
  <%= link_to "Back to pins", pins_path %>
</div>

app/views/pins/index.html.erb
<%# <h1>Pins</h1> %>

<%# <div id="pins"> %>
  <%# <% @pins.each do |pin| %>
    <%# <%= render pin %>
    <%# <p> %>
      <%# <%= link_to "Show this pin", pin %>
    <%# </p> %>
  <%# <% end %>
<%# </div> %>

<main class="pin_container">
<div id="pins_page_next">
 <%# <% @pins.shuffle.each do |pin| %>
<%# <%= render @pins %>
<%# <% end %>
</div>
<%# <%= render "pins/next_page"%>
<%= turbo_frame_tag :pagination, loading: :lazy, src: pins_path(format: :turbo_stream) %>
<%# <%= @pagy.next%>
<%# <%= pagy_url_for(@pagy, @pagy.next) %>


  <div class="scroll_up">
		<svg class="scroll_up_svg" viewbox="-2 -2 52 52">
			<path
				class="scroll_up_svg_path"
				d="
				M24,0
				a24,24 0 0,1 0,48
				a24,24 0 0,1 0,-48
				"
			/>
		</svg>
	</div>
   <%# <%== pagy_next_link(@pagy, text: 'More...', link_extra: 'id="next_link"')%>
   <%# <div id="load_more_button">
  <%= button_to "Load more", pagy_url_for(@pagy, @pagy.next) %>
   <%# </div> %>
</main>

app/views/pins/index.turbo_stream.erb
<%= turbo_stream.append :pins_page_next do %>
   <%= render @pins %>
<% end %>

<%# if @pagy.next.present? %>
<%= turbo_stream.replace :pagination do %>
    <%= turbo_frame_tag :pagination, loading: :lazy, src: pins_path(page: @pagy.next, format: :turbo_stream) %>
<% end %>
<%# end %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render "form", pin: @pin %>

<br>

<div>
  <%= link_to "Back to pins", pins_path %>
</div>

app/views/pins/show.html.erb
<%# <p style="color: green"><%= notice</p>  %>

<%# <%= render @pin %>


  <%# <p> %>
    <%# <%= @pin.description %>
  <%# </p> %>

  <%# <% if @pin.pin_image.attached? %>
    <%# <%= image_tag(@pin.pin_image, width:"90%") %>
  <%# <% end %>


<%# <% if @pin.user == current_user %>
<%# <div> %>
  <%# <%= link_to "Edit this pin", edit_pin_path(@pin) %>
  <%# <%= link_to "Back to pins", pins_path %>

  <%# <%= button_to "Destroy this pin", @pin, method: :delete %>
<%# </div> %>
<%# <% end %>

<%# <% content_for :head do %>
  <%# <%= javascript_importmap_tags%>
  <%# <%= javascript_import_module_tag "scroll" %>
<%# <% end %>

<div class="container_photo_page">
  <div class="band">
    <div class="item-1">
      <div class="card">
        <article>
          <h1><%= @pin.description%></h1>
          <span><%= @pin.user.username %></span>
        </article>
        <div class="thumb">
          <%# <% if @pin.pin_image.attached? %>
            <%= image_tag(@pin.pin_image, width:"100%") %>
          <%# <% end %>
        </div>
        <article>
          <% if @pin.user == current_user %>
            <div>
              <%= link_to "Edit this pin", edit_pin_path(@pin)%>
              <%# <%= link_to "Back to pins", pins_path%>
              <%= button_to "Destroy this pin", @pin, method: :delete %>
            </div>
          <% end %>
          <%= link_to "Back to pins", pins_path%>
        </article>
      </div>
    </div>
  </div>
</div>

  <div class="scroll_up">
		<svg class="scroll_up_svg" viewbox="-2 -2 52 52">
			<path
				class="scroll_up_svg_path"
				d="
				M24,0
				a24,24 0 0,1 0,48
				a24,24 0 0,1 0,-48
				"
			/>
		</svg>
	</div>